### PR TITLE
WIP: Schedule

### PR DESCRIPTION
**Pull request by shaib**
This, for now, includes the skeleton of the agenda, and fixes the symposion/schedule app to work with Python 3.

The schedule is available at the `/schedule` url (it is not bi-lingual, at least yet), which is not linked from the main page. With the PR in its current state, it is just a skeleton. Note that the page generated uses a HTML `<table>` -- but AFAICT it is responsive enough this way.

We still need to review/fix the schedule editing views, even assuming this is all well, and also verify that the presentation works well when there is content.

### CODE REVIEW

**Comment by AmitAronovitch** [comment]
p.s. my version of this branch is at https://github.com/AmitAronovitch/pycon-israel/tree/schedule-fixes
for now they do not diverge much

**Comment by MeirKriheli** [comment]
@shaib The modal is not correct,  the diff for `_slot_edit.html`:

```diff
diff --git a/ilpycon/templates/symposion/schedule/_slot_edit.html b/ilpycon/templates/symposion/schedule/_slot_edit.html
index 1283aab..11058ad 100644
--- a/ilpycon/templates/symposion/schedule/_slot_edit.html
+++ b/ilpycon/templates/symposion/schedule/_slot_edit.html
@@ -1,8 +1,9 @@
 {% load i18n bootstrap %}
-<form id="slotEditForm" class="modal-form" method="POST" action="{% url "schedule_slot_edit" slug slot.pk %}">
+<form id="slotEditForm" class="modal-dialog" method="POST" action="{% url "schedule_slot_edit" slug slot.pk %}">
+  <div class="modal-content">
     <div class="modal-header">
+      <h3 class="modal-title">{% trans "Edit Slot" %}</h3>
       <a class="close" data-dismiss="modal">&times;</a>
-        <h3>{% trans "Edit Slot" %}</h3>
     </div>
     <div class="modal-body" style="height:350px">
       {% csrf_token %}
@@ -11,4 +12,5 @@
     <div class="modal-footer">
       <button type="submit" class="btn btn-primary">Save</button>
     </div>
+  </div>
 </form>
```

**Comment by shaib** [comment]
Thank you so much

**Comment by shaib** [comment]
PR updated with @MeirKriheli's fix of the template and adding the schedule to the navbar. The schedule is added only for logged-in users for now.

Not pushing because late at night, but this should be good to go.

**Pull request merged**
